services:
  phoxicontrol:
    image: ardootala/phoxicontrol
    build: .
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    restart: always
    tty: true
    stdin_open: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/root/ros2_ws
#      - /var/run/dbus:/var/run/dbus
      - /dev/shm:/dev/shm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: stdbuf -o L bash
