services:
  host_phoxi:
    image: ardootala/host-phoxi
    build:
      context: .
      target: host-prod
      args:
        USER: $USER
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    privileged: true
    restart: on-failure
    tty: true
    stdin_open: true
    hostname: DOCKER-PHOXI
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      DBUS_SESSION_BUS_ADDRESS: $DBUS_SESSION_BUS_ADDRESS
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw              # allow connecting to the X server
      - /dev/shm:/dev/shm                             # PhoXi SDK needs this for shared memory
      - /run/user/1001/bus:/run/user/1001/bus
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  dev_container:
    image: ardootala/host-phoxi-dev
    build:
      context: .
      target: dev
      args:
        USER: $USER
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    privileged: true
    restart: always
    tty: true
    stdin_open: true
    hostname: DOCKER-DEV
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw              # allow connecting to the X server
      - ~/.config/tmux:/home/$USER/.config/tmux       # share user configs
      - ~/.config/git:/home/$USER/.config/git         # share user configs
      - ~/.config/nvim:/home/$USER/.config/nvim       # share user configs
      - ~/.config/bash:/home/$USER/.config/bash       # share user configs
      - ~/.ssh:/home/$USER/.ssh                       # share ssh keys for git and remote access
      - /dev/shm:/dev/shm                             # PhoXi SDK needs this for shared memory
      - ros2_dev_phoxi:/home/$USER/ros2_dev           # ros2 root dir
      - ./photoneo_ros2:/home/$USER/ros2_dev/ros_ws/src:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  internal_phoxi:
    image: ardootala/internal-phoxi
    build:
      context: .
      target: standalone
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    privileged: true
    restart: on-failure
    tty: true
    stdin_open: true
    hostname: DOCKER-PHOXI-INTERNAL
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw              # allow connecting to the X server
      - /dev/shm:/dev/shm                             # PhoXi SDK needs this for shared memory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ros2_dev_phoxi:
